variables:
  DIR: /var/www/wiki.homed.dev

Deploy:
  stage: deploy
  script:
  - rm -rf ${DIR}/*
  - python scripts/zigbee.py >> docs/zigbee/devices.md
  - docker run --rm -u ${UID}:${UID} -v ${PWD}:/docs -v ${DIR}:/docs/site squidfunk/mkdocs-material build
  only:
    - master
